# Generated by Django 3.1.6 on 2023-06-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='admission',
            fields=[
                ('srno', models.AutoField(primary_key=True, serialize=False)),
                ('nm', models.CharField(max_length=25)),
                ('dt1', models.DateField()),
                ('emailid', models.CharField(max_length=40)),
            ],
        ),
    ]
